-- V1__init.sql
CREATE TABLE patient (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cpf VARCHAR2(11) NOT NULL UNIQUE,
    email VARCHAR2(255) NOT NULL,
    name VARCHAR2(120) NOT NULL
);

-- Tabela doctor
CREATE TABLE doctor (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    crm VARCHAR2(30) NOT NULL UNIQUE,
    name VARCHAR2(120) NOT NULL
);

-- Tabela appointment
CREATE TABLE appointment (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    doctor_id NUMBER NOT NULL,
    status VARCHAR2(20) NOT NULL,
    date_time TIMESTAMP NOT NULL,
    CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id) REFERENCES patient(id),
    CONSTRAINT fk_appointment_doctor FOREIGN KEY (doctor_id) REFERENCES doctor(id)
);